// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:dcead2d6-75e0-4b63-b681-76c72f14e1e9',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'vaux-hosting-mobilehub-348975445',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd35q7tzvth0s5f.cloudfront.net',
    'aws_mobile_analytics_app_id': 'cbb1605df8a345cf9d2015323920fcb6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '0048c24a-5d06-487b-8c7f-c1876aa192e9',
    'aws_project_name': 'vaux-2018-06-04-20-52-16',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'vaux-mobilehub-348975445',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_pLk5Akmxu',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3iinembeotid80rsm9gcoboi6p',
}

export default awsmobile;
