// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:37990848-970b-4a93-a537-1a5584429ca3',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '1d82363cd01d417ca5fe3233595ff680',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ab28d481-c879-437a-adaf-9f9d5b698f11',
    'aws_project_name': 'vaux ',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'vaux-mobilehub-167575792',
}

export default awsmobile;
